export const ENV_VARS = {
  NEXT_PUBLIC_HTTP_PROTOCOL: process.env.NEXT_PUBLIC_HTTP_PROTOCOL!,
  NEXT_PUBLIC_BACKEND_PUBLIC_PORT: process.env.NEXT_PUBLIC_BACKEND_PUBLIC_PORT!,
  NEXT_PUBLIC_BACKEND_PUBLIC_DOMAIN: process.env.NEXT_PUBLIC_BACKEND_PUBLIC_DOMAIN!,
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME!,
  NEXT_PUBLIC_NODE_ENV_MANUAL: process.env.NEXT_PUBLIC_NODE_ENV_MANUAL!,
} as const
